### PR TITLE
New bug.

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@magland 
Hi Jeremy.
I don't anderstand why because MS4 have change of version but since one or two weeks, MS4 make travis test hangs and so test do not pass.
Maybe a package on wich MS4 depend change the behavior (like isosplit5).
Do you have an idea what could have change ?
This PR block for this and make the doc of spikeinterface no building. Could you have a look with a fresh install in an isolated env ?

**Comment by samuelgarcia** [comment]
@alejoe91 @colehurwitz We must merge this before relase!!!

**Comment by alejoe91** [comment]
Why is it failing?

**Comment by samuelgarcia** [comment]
MS4 hangs.

**Comment by samuelgarcia** [comment]
Wait. Not this time. I launch again the travis.

**Comment by samuelgarcia** [comment]
I think now it is HS that do crash.

**Pull request merged**
