### PR TITLE
Add support for Kilosort2.5

### PR DESCRIPTION
**Pull request by alowet**
I copied and modified Kilosort2Sorter to support Kilosort2.5. This is now called Kilosort2_5Sorter and runs on the path specified by environment variable KILOSORT2_5_PATH. In this way, it remains completely separate from Kilosort2 and each can run independently.

### CODE REVIEW

**Comment by alejoe91** [comment]
Thanks @alowet 

This is awesome!!! Do you know if there are new parameters involved in the drift correction? Maybe we should expose those to the user. 

Otherwise it looks great! Have you tested it and does it work as expected? 👍 

Cheers
Alessio

**Comment by alowet** [comment]
Yes, there are two new parameters in Kilosort2.5: `nblocks` and `sig`. (In fact, Kilosort2.5 doesn't work without them, which is part of the reason why I thought it would be cleaner to make a completely new Sorter as opposed to hacking together a modification to the Kilosort2Sorter with a bunch of exceptions.) Both have to do with the subpixel registration process. I added the default values (5 and 20, respectively) to `_default_params` and descriptions to `_params_description`. They are exposed to the user and I confirmed that they can be overwritten if desired. I tested the code on a sample SpikeGLX recording and it works as expected.

**Comment by alejoe91** [comment]
> Yes, there are two new parameters in Kilosort2.5: `nblocks` and `sig`. (In fact, Kilosort2.5 doesn't work without them, which is part of the reason why I thought it would be cleaner to make a completely new Sorter as opposed to hacking together a modification to the Kilosort2Sorter with a bunch of exceptions.) Both have to do with the subpixel registration process. I added the default values (5 and 20, respectively) to `_default_params` and descriptions to `_params_description`. They are exposed to the user and I confirmed that they can be overwritten if desired. I tested the code on a sample SpikeGLX recording and it works as expected.

Amazing!! Merging it then :) Can't wait to test it too!

**Comment by alowet** [comment]
Awesome, thanks for creating such a wonderful toolbox!

**Pull request merged**
