### PR TITLE
sorter using a new feature of waveclus 

### PR DESCRIPTION
**Pull request by ferchaure**
Hi guys,

I have been using this for a while and I forgot to do a pull request. The sorter uses a new feature of wave_clus  ( It doesn't save the detected spikes in the results file). This will make a bit faster the use of the sorter.

### CODE REVIEW

**Comment by alejoe91** [comment]
Thanks @ferchaure 

The problem in tests is due the new matlotlib version.. can you force it to 3.2.2 in the .travis?

**Comment by ferchaure** [comment]
It doesn't work... or I didn't know how to do it properly

**Comment by alejoe91** [comment]
Mmm now spyking circus is failing...

**Comment by alejoe91** [comment]
Disabled SC tests for now :)

**Pull request merged**
