### PR TITLE
Spike detection

### PR DESCRIPTION
**Pull request by alejoe91**
Implemented a simple spike detection by channel as requested in https://github.com/SpikeInterface/spikesorters/issues/75

The spike detection looks for peaks (negatice, bositive, or both) above detect_threshold*MAD and finds the peak time for each spike.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
I think this is the wring place.
I would do it in spiketoolkit
.

**Comment by alejoe91** [comment]
It's not really a preprocessing nor a postprocessing. This is for like low density mess to detect mua. I think it belong here!

**Comment by samuelgarcia** [comment]
I still think it would be better in spiketoolkit.
toolkit is a tool kit of processing (pre post, what ever).
spike detection is a processing step.
spikesorter is mainly  a wrapper collection and launcher tools.

**Comment by alejoe91** [comment]
Where would you place it in spiketoolkit?

**Comment by samuelgarcia** [comment]
spiketoolkit.detection ?

**Comment by samuelgarcia** [comment]
In my mind, we could be able to make a new sorter based just on spiketoolkit element (filtering, pca, whitening...). Spike detection belong to this.

**Comment by alejoe91** [comment]
> In my mind, we could be able to make a new sorter based just on spiketoolkit element (filtering, pca, whitening...). Spike detection belong to this.

Yes I think we could have something like that. And they would be sorter_tools :)

**Comment by alejoe91** [comment]
@samuelgarcia the detect_spikes takes a recording extractor as input and outputs a sorting extractor. I think it doesn't belong to spiketoolkit for this reason. 

If we make a new spike sorter then I think it's fine that basic processing is in toolkit (filter / whiten) and spike sorting related stuff are in spikesorters (detect / cluster).

What do you guys think? @colehurwitz @magland @mhhennig ?

**Comment by magland** [comment]
This is tricky. I can see advantages of both options.

If I were to vote I would say.... put it in spiketoolkit. Because it is not
a full sorting, only one piece of a sorting.

**Comment by alejoe91** [comment]
in the preprocessing? Or should we make another module? I think it's tricky to assign it to the modules we have now...

**Comment by magland** [comment]
I agree. Tricky. Does not fit into existing categories. Not sure.

**Comment by alejoe91** [comment]
Moved here: https://github.com/SpikeInterface/spiketoolkit/pull/292

**Pull request closed without merging**
