### PR TITLE
Update for 0.9.0

### PR DESCRIPTION
**Pull request by yger**

### CODE REVIEW

**Comment by yger** [comment]
Minor changes in the .params file in order to work with 0.9.0

**Comment by magland** [comment]
I merged this and built the docker image. Do I need to wait for something
to change in spikeinterface or is this good to go?

**Comment by yger** [comment]
I don't know why the checks for this PR are failing. There is a minor change in the default parameters of SC, propagated in this PR, but this is it, and since the 0.9.0 release has been made via pip/conda, it should work. But everything will work without the PR anyway.

**Comment by yger** [comment]
Maybe to be consistant, just wait for this PR to be approuved, in order to really be in sync

**Comment by yger** [comment]
Can the checks on Travis be relaunched and the PR merged? Not sure they are failling because of the PR in fact..

**Comment by alejoe91** [comment]
Hi @yger it looks like pyqt is failing to install when tdc tries to install it.
@samuelgarcia seen this error before? 

@yger can you try to add python 3.7 in travis a longside with 3.6? wondering if it's due to 3.6 and the latest pyqt version

**Comment by yger** [comment]
Not better with py3.7. I'm not sure of what I can do to propagate the PR, since I don't know how I could bypass this Travis issue.... Where are all the dependencies listed (alongside with the versions)?

**Comment by alejoe91** [comment]
It seems to be coming from TDC no? @samuelgarcia ?

**Comment by samuelgarcia** [comment]
Hi Pierre.
It looks like a PyQt5 installation error.
Can you force to previous version ? like 5.13
this is also in requirement_sorter.txt add a line under tridesclous.

**Comment by alejoe91** [comment]
Great! Can I merge?

**Comment by yger** [comment]
Yes, fine for me!

**Pull request merged**
