### PR TITLE
Enabled SC test on travis

### PR DESCRIPTION
**Pull request by alejoe91**
- install mpich
- force SC==0.8.0

### CODE REVIEW

**Comment by yger** [comment]
What is the error? Have a look to the .travis.yaml file in the root folder of SpyKING CIRCUS. We are able to install it automatically, but I admit this is not easy.  I just pushed 0.8.1, so let's start from that, with merging included in the default pipeline. After the talks at the workshop, I felt like I had to do something :-)

**Comment by yger** [comment]
You should have scipy==1.2 (since statsmodel is not yet changed to work with 1.3)

conda install --yes --quiet tqdm mpi4py "mpich>=3" numpy cython "scipy==1.2" matplotlib h5py colorama psutil qt libgcc pyqt python-blosc statsmodels scikit-learn

**Comment by alejoe91** [comment]
We kind of want to avoid installing from conda :)

I tried to force scipy 1.2, sc 0.8.1, and adde libmpi-dev. Let's see what happens!

Good that the workshop helped! I think we will all benefit from it! Now developers are stressed eheheh

**Comment by alejoe91** [comment]
This is the error:

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/spyking-circus", line 7, in <module>
    from circus.scripts.launch import main
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/circus/scripts/launch.py", line 22, in <module>
    from circus.shared.files import data_stats
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/circus/shared/__init__.py", line 12, in <module>
    from . import files
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/circus/shared/files.py", line 5, in <module>
    from circus.shared.utils import get_tqdm_progressbar
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/circus/shared/utils.py", line 17, in <module>
    from .mpi import gather_array, all_gather_array, comm, SHARED_MEMORY
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/circus/shared/mpi.py", line 4, in <module>
    from mpi4py import MPI
ImportError: libmpi.so.1: cannot open shared object file: No such file or directory
```

**Comment by yger** [comment]
MPI4py can be compiled either with mpich or with openmpi. I guess the
problem is that, if you install it with pip, it may comes with some already
compiled binaries assuming you have openmpi. So in my case, I always
install MPI4py from sources. It seems to be related to the discussion here

https://bitbucket.org/mpi4py/mpi4py/issues/76/mpi4py-with-mpich-doesnt-not-seems-to-work

So the solution is to add --no-binary=mpi4py when installing with pip

Le sam. 29 juin 2019 à 12:59, Alessio Buccino <notifications@github.com> a
écrit :

**Comment by alejoe91** [comment]
you mean `pip install spyking-circus==0.8.1 --no-binary=mpy4py`?

**Comment by yger** [comment]
I guess, yes. As said, I don't do that since I installed MPI4py from
sources. But based on the discussion on the link I gave you, this should
work and prevent MPI4py, installed with pip, to bring any precompiled binary

Le sam. 29 juin 2019 à 13:12, Alessio Buccino <notifications@github.com> a
écrit :

**Comment by alejoe91** [comment]
So I don't habe to install the dependencies from travis?
I can just have:

`sudo apt install libmpich-dev`

and 

`pip install spyking-circus==0.8.1 --no-binary=mpi4py`

If you don't mind I'll propagate your change son this PR.

**Comment by yger** [comment]
Yes, in theory this should work. I'm not in front of a computer right now,
but I can test that later in the afternoon

Le sam. 29 juin 2019 à 13:20, Alessio Buccino <notifications@github.com> a
écrit :

**Comment by alejoe91** [comment]
Almost fixed!!!!

**Comment by alejoe91** [comment]
@yger et voila!

could you please double check that I made all the changes that you made in the othter PR?
I also changed n_cores --> num_workers (same as ms4), added the auto_merge param (default 0.5) and by default now it uses all the cores. If you are ok with this I'll merge :)

**Comment by samuelgarcia** [comment]
@yger: un petit coup chaud ?

**Comment by yger** [comment]
Oui on va dire ça ! Tu m'enverrais ta présentation d'Edimburgh ?

Le lun. 1 juil. 2019 à 09:57, Garcia Samuel <notifications@github.com> a
écrit :

**Comment by alejoe91** [comment]
https://www.spikeforum.org/t/spikeinterface-presentation-hurwitz/

**Comment by yger** [comment]
Thanks a lot !

This automation quest is really helpful, so I'll try to get involve by
writing some metrics too.

Le lun. 1 juil. 2019 à 10:07, Alessio Buccino <notifications@github.com> a
écrit :

**Pull request merged**
