### PR TITLE
fix manifest.in to ensure that *.prm files are included in pypi package

### PR DESCRIPTION
**Pull request by magland**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Oups. thank you for seen it.

**Comment by samuelgarcia** [comment]
@alejoe91 : do you known why do we so much travis runnnig ?
It is bad for our green footprint.

**Comment by alejoe91** [comment]
@magland  thanks!! merging :)

@samuelgarcia we can set the triggers in the repo. When should we trigger a travis run?

**Comment by samuelgarcia** [comment]
Only for PR I think. Not branch.
I don't known what is this continuous-integratioçn/travis-ci/pr.
It add 2 more run.

**Comment by alejoe91** [comment]
ok I'll make a new release and fix the travis run (only on PR and tags)

**Comment by alejoe91** [comment]
https://pypi.org/project/spikesorters/

**Comment by samuelgarcia** [comment]
Tu es un champion.

**Comment by magland** [comment]
Thanks! It works... and sf analysis is now re-running (at a rate of 150 simultaneous jobs). ... and it's also first time using st for gr truth comparison.

**Comment by samuelgarcia** [comment]
Congrate @magland you are super efficient.

**Pull request merged**
