### PR TITLE
ironclust default parameters updated (v5.8.5)

### PR DESCRIPTION
**Pull request by jamesjun**
I exposed four more parameters and changed default values for IronClust (v5.8.5).

### CODE REVIEW

**Comment by alejoe91** [comment]
Thanks @jamesjun!

@colehurwitz why is the test failing?

**Comment by colehurwitz** [comment]
Looks like a recent change @mhhennig made. Could you take a look? Also, we will push a new pypi version to turn off all the comments (it is in debug mode).

**Comment by alejoe91** [comment]
@jamesjun maybe merging with master would fix it?

**Comment by colehurwitz** [comment]
I think it is a spikeextractors issue. Matthias made some recent changes that may be failing.

**Comment by samuelgarcia** [comment]
@mhhennig the travis is still buggy.

**Pull request merged**
