### PR TITLE
[WIP] Fixing travis tests

### PR DESCRIPTION
**Pull request by colehurwitz**
I added back the failing herdingspikes and ms4 tests (the third test, binary extractor, fails for hs2 and times out for ms4).

Hopefully, we can solve the issues here. I think we will need @magland to help with this since we are not sure what is going on with ms4.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@colehurwitz : when you comment in the **\_\_main\_\_** it do not impact if test are launch or not.

This is just a convinient when you debug a a test, you just run the script.

Test are launch with **pytest** command outside the **\_\_main\_\_**

If you want to disable a test you need to add a decorator with ```@pytest.mark.skipif(...)```

**Comment by colehurwitz** [comment]
Ok, good to know, thanks @samuelgarcia . I will try to do that in the future.

**Comment by samuelgarcia** [comment]
I think we can close this #146 remove the fail on HS2.
I just remove the paralell compute when groups.

**Comment by samuelgarcia** [comment]
I close this.

**Pull request closed without merging**
