### PR TITLE
Minor updates in parameter file

### PR DESCRIPTION
**Pull request by yger**
MInor modifications of the parameter file for SC 0.8.4, just released via pip/conda

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi pierre can you rebase this because you need to explicitly put the version in
**requirements_sorters.txt** file to get travis pass test.

**Comment by yger** [comment]
If the PR can be merged, then go for it, since I've updated the param file for 0.8.5

**Comment by samuelgarcia** [comment]
You don't pass travis test.
Could you check it ?

**Comment by yger** [comment]
I found the issue, and sadly I'll need to make a 0.8.6 release just to pass your test suite, otherwise now the default behavior was requiring a key pressed by the user, not to overwrite results. Will do that asap

**Comment by samuelgarcia** [comment]
And don't forget to change requirements_sorters.txt  here after the release.

**Comment by alejoe91** [comment]
Thank you @yger!

Ready to merge now?

**Comment by yger** [comment]
Yes!

**Comment by yger** [comment]
Thanks! No major changes here, but please tell me again if there is something more to do to propagate such a change in spikeforest. Simply make a PR with an update on the docker container? Spikesorters is now used by spikeforest, in theory, so changes should be automatically propagated

**Comment by samuelgarcia** [comment]
Yes to propagate to SF, you need to make a new docker that explicitly install the good version of:
  * circus (you need to make a release)

In your docker spikesorter is installed with github so no need to release.

https://github.com/flatironinstitute/spikeforest/blob/master/spikeforest/spikeforestsorters/spyking_circus/container/Dockerfile

**Pull request merged**
