### PR TITLE
ms4 sampling frequency

### PR DESCRIPTION
**Pull request by alejoe91**

### CODE REVIEW

**Comment by alejoe91** [comment]
add `sorting.set_sampling_frequency()` to get results

**Comment by samuelgarcia** [comment]
@alejoe91  : this solve the problem only when evrything is in memory.

In my main usecase I call **get_result_from_folder** (for instance in study) in another pyhton session where recordings do not exists anymore. So sampling rate is not read back in that case.

**Comment by alejoe91** [comment]
I know.. I suggested to @magland to change the mdaextractor, but we agreed it's too late to change the format.

**Comment by magland** [comment]
I suggest to make samplerate (or sampling_frequency) a mandatory parameter of the constructor of MdaSortingExtractor. Any time you create such an object, the sampling freq. should be available somehow by an accompanying recording extractor.

**Comment by samuelgarcia** [comment]
I think it is better to postpone the mandatory sampling rate kargs at SortingComparison, no ?
This is more flexible, a sorting could be use for something else that comparison.
What do you think ?
If in groundTruthComparison, the rule is at least one sorting must handle the sample rate then we are flexible and there is no pain for the user to propagate the sampling rate by itself.

**Pull request merged**
