### PR TITLE
[WIP] Remove cycli dep : add spiketoolkit as dep

### PR DESCRIPTION
**Pull request by samuelgarcia**
Remove cycli dep : add spiketoolkit as dep.
This must be merge when spiketoolkit will be released.

Accidentaly, this PR also include the versionning of sorters.
I am sorry. Would you be agree to merge everthing at once because I lost the branch ....

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@alejoe91 : here there is 2 travis, my guess is:
  * the first one is automatic because we have ".travis.yml" file in the folder
  * the second one is done manually in travis itself.

We should remove the second one, the first one fully integrated in GH.

For spikecomparison, I only put the file and before wondering how to do the setup in travis it was already done magically only with the file !!!

**Comment by alejoe91** [comment]
Should I remove the webhook? I'll give it a try.

The test fail because it should be `tdc.__version__`  here: https://github.com/samuelgarcia/spikesorters/blob/new_features/spikesorters/tridesclous/tridesclous.py#L75

**Comment by alejoe91** [comment]
@samuelgarcia  you mean there are 2 folders called spikesorters in travis or you have continuous-integration/travis-ci/pr and Travis CI - Pull Request ? How do you remove one?

**Comment by samuelgarcia** [comment]
I mean 2 CI:
  * continuous-integration/travis-ci/pr : the manual one you have settle
 * Travis CI : the auto one

Wer should remove the manual one no ? I don't how to d it of course :)

**Comment by alejoe91** [comment]
I can try to remove the webhook...can you make another commit in 1 minute?

**Comment by alejoe91** [comment]
no I actually think that is a bad idea..

**Comment by samuelgarcia** [comment]
Any reason ?

**Comment by samuelgarcia** [comment]
If you are OK to merge this mixed PR. We could then release all the family package and make an alphe spikeinterface package.

**Comment by alejoe91** [comment]
Yes. I think that in the future for the matlab based sorters we could run a `git log` internally and return the last commit. I don't know if it works if you download as zip, but in that case we can throw an error. What do yout think?

**Pull request merged**
