### PR TITLE
New waveclus spikesorter, remove argument for Matlab on windows

### PR DESCRIPTION
**Pull request by ferchaure**
I fixed an error updating the parameters and removed the conversion to and from mda used by the old wrapper, now it uses the WaveClusSortingExtractor.

I removed the '-nodisplay' because it doesn't exist as an argument for Matlab on windows.

### CODE REVIEW

**Comment by alejoe91** [comment]
Thanks @ferchaure 

Ready to merge? Looks good to me :)

**Comment by alejoe91** [comment]
@ferchaure let me know when I should merge

**Comment by ferchaure** [comment]
Sorry, It's done. No more commits on the sorters... for know :smile: 

I keep thinking about implementing the sorters using the Matlab engine API for python, but probably the best way to do it should be sharing an engine across all spikeinterface, and that part will be tricky.

**Comment by alejoe91** [comment]
> Sorry, It's done. No more commits on the sorters... for now 😄
> 
> I keep thinking about implementing the sorters using the Matlab engine API for python, but probably the best way to do it should be sharing an engine across all spikeinterface, and that part will be tricky.

Let's discuss that on another issue :)

**Pull request merged**
