### PR TITLE
fix renamed installed method on wc

### PR DESCRIPTION
**Pull request by ferchaure**
Hi Guys, one of the last commits broke the waveclus sorter.  This little change fixes it

### CODE REVIEW

**Comment by samuelgarcia** [comment]
oups. sorry i missed that line.
thanks to see it.
will merge it after travis.

**Comment by alejoe91** [comment]
Thank you @ferchaure!! Sorry to have missed it!

**Comment by samuelgarcia** [comment]
alessio you are a bad reviewer :)

**Comment by alejoe91** [comment]
> alessio you are a bad reviewer :)

and you are a bad programmer!! :)

**Comment by samuelgarcia** [comment]
sure.

**Pull request merged**
