### PR TITLE
Refractoring: Using ShellScript, Waveclus, Updated KS2 params

### PR DESCRIPTION
**Pull request by alejoe91**

### CODE REVIEW

**Comment by alejoe91** [comment]
Also updating the other sorters with ShellScript (WIP)

**Comment by alejoe91** [comment]
@ferchaure  can you check if the wave_clus implementation looks correct? I was able to run it both on multiple electrodes and single channel amd it seems to give reasonable results.

Does wave_clus use location information? 

Also, I exposed a few [params](https://github.com/SpikeInterface/spikesorters/blob/waveclus/spikesorters/waveclus/waveclus.py#L35-L40). Should I add some more?

**Comment by ferchaure** [comment]
About the parameters, I would include: min_clus, maxtemp and template_sdnum.

**Comment by alejoe91** [comment]
this is ready after merging https://github.com/SpikeInterface/spikeextractors/pull/261

**Comment by samuelgarcia** [comment]
Hi Alessio.
This look very cool.
2 questions:
  * I don't andestand why is there 2 waveclust wrappers.
  * is the ShellScript class able to catch matlab errors ? Because matlab can have an error and 
    quit silently no ?

I think we should also as we discussed try to read the output folder to check if results are readable and if not raise an error so it could be catch by GTStudy for instance.

**Comment by alejoe91** [comment]
@samuelgarcia I'll remove the second waveclus (from SF)

The matlab scripts are now made so that if they fail they return 1 (https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/kilosort2/kilosort2_master.m)

We should be good! Will merge spikeextractors and then this

**Comment by samuelgarcia** [comment]
Cool.
I did not read matlab code sorry.
Very good approach.

**Comment by alejoe91** [comment]
Thank @magland :)

**Comment by alejoe91** [comment]
merging

**Comment by samuelgarcia** [comment]
COuld you also update this page https://spikeinterface.readthedocs.io/en/latest/sortersinfo.html
in spikeinterface by adding waveclust ?

**Pull request merged**
