### PR TITLE
IronClust default parameters changed

### PR DESCRIPTION
**Pull request by jamesjun**

### CODE REVIEW

**Comment by colehurwitz** [comment]
Hi @jamesjun , I just introduced a change in the master branch to skip both the herdingspikes and mountainsort tests, if you could update with master, then I think all the tests should pass. We are working to get these tests re-integrated in a different branch.

**Comment by alejoe91** [comment]
@jamesjun can you merge with the current master? It should fix the tests. Then we can merge :)

**Comment by samuelgarcia** [comment]
Hi @jamesjun. I plan to make a release today if you rebase it to the master this PR could incorporated.
Best

**Comment by jamesjun** [comment]
Please give me a permission to update SpikeInterface/spikesorters. I
updated the default parameters

    _default_params = dict(
>         detect_sign=-1,  # Use -1, 0, or 1, depending on the sign of the
> spikes in the recording
>         adjacency_radius=50,  # Use -1 to include all channels in every
> neighborhood
>         adjacency_radius_out=75,  # Use -1 to include all channels in
> every neighborhood
>         detect_threshold=4,  # detection threshold
>         prm_template_name='',  # .prm template file name
>         freq_min=300,
>         freq_max=8000,
>         merge_thresh=0.99,  # Threshold for automated merging
>         pc_per_chan=0,  # Number of principal components per channel
>         whiten=False,  # Whether to do channel whitening as part of
> preprocessing
>         filter_type='bandpass',  # none, bandpass, wiener, fftdiff, ndiff
>         filter_detect_type='none',  # none, bandpass, wiener, fftdiff,
> ndiff
>         common_ref_type='mean',  # none, mean, median
>         batch_sec_drift=300,  # batch duration in seconds. clustering time
> duration
>         step_sec_drift=20,  # compute anatomical similarity every n sec
>         knn=30,  # K nearest neighbors
>         min_count=30,  # Minimum cluster size
>         fGpu=True,  # Use GPU if available
>         fft_thresh=8,  # FFT-based noise peak threshold
>         fft_thresh_low=0,  # FFT-based noise peak lower threshold (set to
> 0 to disable dual thresholding scheme)
>         nSites_whiten=32,  # Number of adjacent channels to whiten
>         feature_type='gpca',  # gpca, pca, vpp, vmin, vminmax, cov,
> energy, xcov
>         delta_cut=1,  # Cluster detection threshold (delta-cutoff)
>         post_merge_mode=1,  # post merge mode
>         sort_mode=1  # sort mode
>     )



-James

**Comment by alejoe91** [comment]
Hi @jamesjun if you commit to your [branch](https://github.com/jamesjun/spikesorters) it should update this PR.

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikesorters/pull/81

**Pull request merged**
