### PR TITLE
adds combinato sorter

### PR DESCRIPTION
**Pull request by ferchaure**
Hi guys, this code adds support for the sorter combinato.

It is required to set the path of the combinato code to work, like for ironclus, wave_clus, etc. Combinato can't be installed using pip, at least for now.

Probably the descriptions of the sorter and parameters can be improved... I just copy-pasted them and added my broken English on top

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Fernando. this is really cool.
I will have a look soon and make some benchmark as well :)

**Comment by alejoe91** [comment]
@ferchaure @samuelgarcia can we merge this?

**Comment by samuelgarcia** [comment]
This looks good.
I think you can.
When yass will be also merge, I will run new benchmark with theses 2 news sorters.

**Comment by ferchaure** [comment]
Yes, you can merge

**Comment by timsainb** [comment]
It looks like this implementation isn't finished? Why is only channel 1 added to the h5 file in `_setup_recording`

```python
# Generate h5 files in the dataset directory
chid = recording.get_channel_ids()[0]
vcFile_h5 = str(output_folder / ('recording.h5'))
f = h5py.File(vcFile_h5, mode='w')
f.create_dataset("sr", data=[recording.get_sampling_frequency()], dtype='float32')

f.create_dataset("data", data=recording.get_traces(channel_ids=[chid]).flatten())
f.close()
```

Is there no implementation for writing the recording to h5?

**Comment by timsainb** [comment]
That code should be replaced with write_to_h5_dataset_format, as in hdsort: https://github.com/SpikeInterface/spikesorters/blob/0d4ca7718e786720bdf55285d0f0bc3bf9dff9c2/spikesorters/hdsort/hdsort.py#L249

**Comment by ferchaure** [comment]
combinato is a single channel sorter, but you are right I should create a recording for each channel to support recordings with multiple channels.

**Comment by ferchaure** [comment]
The issue is how to merge the single-channel results in one sortingextractor... @samuelgarcia  do you think that using a multisortingextractor will be the best way to highlight that is just a combination of single- channel results and not a proper sorting of the full recording?

**Comment by alejoe91** [comment]
@ferchaure I think we can use a MultiSortingExtractor, but we should print a big warning when combinato is run on multiple channel data..especially with locations

**Comment by ferchaure** [comment]
ok, should I add a 'ch_id' property to each sorting in the MultiSortingExtractor to know to which channel is related?

**Comment by alejoe91** [comment]
Yes, maybe 'channel_id' ;)

**Comment by timsainb** [comment]
Looks good!
I still think that you should replace `recording.get_traces` with `recording.write_to_h5_dataset_format`, as I believe the current method loads the whole recording into RAM. 


https://github.com/SpikeInterface/spikesorters/blob/0d4ca7718e786720bdf55285d0f0bc3bf9dff9c2/spikesorters/combinato/combinato.py#L128-L132
to something like this

https://github.com/SpikeInterface/spikesorters/blob/0d4ca7718e786720bdf55285d0f0bc3bf9dff9c2/spikesorters/hdsort/hdsort.py#L249-L264

**Comment by ferchaure** [comment]
then the new way should be using `recording.write_to_h5_dataset_format`? the h5 file will be identical?

**Comment by timsainb** [comment]
Yes, this way just writes via chunks as far as I'm aware!

**Comment by alejoe91** [comment]
Exactly! It should be the same evite with the possibility to write in chunks :) thanks guys!

**Comment by ferchaure** [comment]
I have an issue with write_to_h5_dataset_format, it always save the recording as a 2 dimensional array, and internally combinato requires 1 dimensional data... any ideas?

**Comment by timsainb** [comment]
Ah, that's annoying. In the `write_to_h5_dataset_format` code I would add a flat_channel argument (or something like that) that just writes a 1D array. 

https://github.com/SpikeInterface/spikeinterface/blob/6a96af58ddd607555b8ddba783fb7e7b747a7e81/spikeinterface/core/core_tools.py#L349

**Comment by ferchaure** [comment]
I closed the pull request https://github.com/SpikeInterface/spikesorters/pull/219

**Pull request merged**
