### PR TITLE
New parameters for 0.8.3

### PR DESCRIPTION
**Pull request by yger**
Patching some flaws of the software for small/short/noisy datasets, I made a 0.8.3 release, that I hope should enahce the results of SpyKING CIRCUS with respect to automatic evaluation. At least, it should make the confusion matrices more square, by removing obvious noisy templates :-) Thanks a lot for taking that into account (if not already merged with SpikeForest? I made two separate PR...)

### CODE REVIEW

**Comment by alejoe91** [comment]
Hi Pierre :)

Thanks for the PR.  SpikeForest is using this wrapper now so no need to duplicate efforts. 

Could you try to merge with the master branch to solve the merge conflicts? They are small ones, but I think it's cleaner that way.
In the master I already set the merge to True and added the auto_merge param. Moreover the `n_cores` is now `num_workers` (consistent across sorters) https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/spyking_circus/spyking_circus.py#L32-L34

Also can you set 0.8.3 in the `.travis`?

Cheers
Alessio

**Comment by yger** [comment]
Sure, sorry for having mixed versions. Should be fine now

**Comment by alejoe91** [comment]
Yep :) just waiting for the tests and merging!

**Comment by magland** [comment]
I will rebuild the container on spikeforest and point to this commit (e5b275dba262719cf6947e9092b3363fc63dcbcb)

**Pull request merged**
