### PR TITLE
Gui params added to all sorters

### PR DESCRIPTION
**Pull request by colehurwitz**
I added GUI params to all sorters based off the versions from master. I might need to update them for the new matlab sorters? Not sure.

For now, I think we keep GUI params as separate parameters, but it would be nice to integrate them with default params if possible to avoid duplication and potentialy mismatch between the GUI and spiketoolkit.

### CODE REVIEW

**Comment by colehurwitz** [comment]
Any ideas why the builds are failing? Do you think we could fix all of these builds before releasing on Sunday? @alejoe91 @samuelgarcia @magland

**Comment by alejoe91** [comment]
@colehurwitz I think you are not accessing gui params right. It should be Sorter class._extra_gui_params

**Comment by alejoe91** [comment]
@colehurwitz I think you are not accessing gui params right. It should be Sorter class._extra_gui_params. the problem seems to be in tridesclous only

**Comment by colehurwitz** [comment]
I don't see any issues with gui_params actually. If you look, I add all the "extra" params into the original gui_params in the same way for each class.

**Comment by colehurwitz** [comment]
It appears to be an issue like this:

The following packages have unmet dependencies:
 qt5-default : Depends: qtbase5-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
apt-get.diagnostics
apt-get install failed
$ cat ${TRAVIS_HOME}/apt-get-update.log
Get:2 http://security.ubuntu.com/ubuntu trusty-security InRelease [65.9 kB]
Get:3 http://dl.hhvm.com/ubuntu trusty InRelease [3,106 B]
Get:4 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease [15.4 kB]
Get:6 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease [56.5 kB]
Get:1 http://dl.bintray.com/apache/cassandra 39x InRelease [3,168 B]
Ign:7 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 InRelease
Get:8 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release [2,495 B]
Get:9 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release.gpg [801 B]
Get:10 http://dl.hhvm.com/ubuntu trusty/main amd64 Packages [1,819 B]
Ign:5 http://heroku-toolbelt.s3.amazonaws.com/apt ./ InRelease
Get:11 http://heroku-toolbelt.s3.amazonaws.com/apt ./ Release [1,609 B]
Get:12 http://heroku-toolbelt.s3.amazonaws.com/apt ./ Release.gpg [473 B]
Ign:13 http://archive.ubuntu.com/ubuntu trusty InRelease
Ign:14 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease
Get:15 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease [20.8 kB]
Get:16 http://archive.ubuntu.com/ubuntu trusty-updates InRelease [65.9 kB]
Get:17 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease [15.4 kB]
Get:18 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease [15.4 kB]
Get:19 http://apt.postgresql.org/pub/repos/apt trusty-pgdg/main amd64 Packages [201 kB]
Get:20 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease [15.5 kB]
Get:21 http://archive.ubuntu.com/ubuntu trusty-backports InRelease [65.9 kB]
Get:22 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main amd64 Packages [1,843 B]
Get:23 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main i386 Packages [1,842 B]
Get:24 http://archive.ubuntu.com/ubuntu trusty Release [58.5 kB]
Get:25 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main Translation-en [990 B]
Get:26 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release [15.1 kB]
Get:27 http://apt.postgresql.org/pub/repos/apt trusty-pgdg/main i386 Packages [201 kB]
Get:28 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release.gpg [316 B]
Get:29 http://archive.ubuntu.com/ubuntu trusty Release.gpg [933 B]
Ign:30 http://dl.google.com/linux/chrome/deb stable InRelease
Get:31 http://dl.google.com/linux/chrome/deb stable Release [943 B]
Get:32 http://dl.google.com/linux/chrome/deb stable Release.gpg [819 B]
Get:33 http://dl.bintray.com/apache/cassandra 39x/main amd64 Packages [682 B]
Get:34 http://dl.bintray.com/apache/cassandra 39x/main i386 Packages [682 B]
Get:35 https://download.docker.com/linux/ubuntu trusty InRelease [37.1 kB]
Get:36 http://security.ubuntu.com/ubuntu trusty-security/main Sources [220 kB]
Get:37 http://security.ubuntu.com/ubuntu trusty-security/restricted Sources [5,050 B]
Get:38 http://security.ubuntu.com/ubuntu trusty-security/universe Sources [126 kB]
Get:39 http://security.ubuntu.com/ubuntu trusty-security/multiverse Sources [3,070 B]
Get:40 http://security.ubuntu.com/ubuntu trusty-security/main amd64 Packages [1,032 kB]
Get:41 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4/multiverse amd64 Packages [14.1 kB]
Get:42 http://security.ubuntu.com/ubuntu trusty-security/main i386 Packages [934 kB]
Get:44 http://security.ubuntu.com/ubuntu trusty-security/main Translation-en [541 kB]
Get:43 http://heroku-toolbelt.s3.amazonaws.com/apt ./ Packages [636 B]
Get:45 http://security.ubuntu.com/ubuntu trusty-security/restricted amd64 Packages [18.1 kB]
Get:46 http://security.ubuntu.com/ubuntu trusty-security/restricted i386 Packages [17.8 kB]
Get:47 http://security.ubuntu.com/ubuntu trusty-security/restricted Translation-en [3,272 B]
Get:48 http://security.ubuntu.com/ubuntu trusty-security/universe amd64 Packages [377 kB]
Get:49 http://security.ubuntu.com/ubuntu trusty-security/universe i386 Packages [355 kB]
Get:50 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main amd64 Packages [3,494 B]
Get:51 http://security.ubuntu.com/ubuntu trusty-security/universe Translation-en [203 kB]
Get:52 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main i386 Packages [3,496 B]
Get:53 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main Translation-en [2,368 B]
Get:54 http://security.ubuntu.com/ubuntu trusty-security/multiverse amd64 Packages [4,730 B]
Get:55 http://security.ubuntu.com/ubuntu trusty-security/multiverse i386 Packages [4,887 B]
Get:56 http://security.ubuntu.com/ubuntu trusty-security/multiverse Translation-en [2,426 B]
Get:57 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main amd64 Packages [7,578 B]
Get:58 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main i386 Packages [7,708 B]
Get:59 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main Translation-en [2,535 B]
Get:60 http://archive.ubuntu.com/ubuntu trusty-updates/main Sources [532 kB]
Get:61 http://archive.ubuntu.com/ubuntu trusty-updates/restricted Sources [6,444 B]
Get:62 http://archive.ubuntu.com/ubuntu trusty-updates/universe Sources [288 kB]
Get:63 http://archive.ubuntu.com/ubuntu trusty-updates/multiverse Sources [7,389 B]
Get:64 http://archive.ubuntu.com/ubuntu trusty-updates/main amd64 Packages [1,460 kB]
Get:65 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease [23.5 kB]
Get:66 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main amd64 Packages [430 B]
Get:67 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main i386 Packages [430 B]
Get:68 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main Translation-en [374 B]
Ign:64 http://archive.ubuntu.com/ubuntu trusty-updates/main amd64 Packages
Get:69 http://archive.ubuntu.com/ubuntu trusty-updates/main i386 Packages [1,354 kB]
Ign:69 http://archive.ubuntu.com/ubuntu trusty-updates/main i386 Packages
Get:70 http://archive.ubuntu.com/ubuntu trusty-updates/main Translation-en [701 kB]
Get:71 http://archive.ubuntu.com/ubuntu trusty-updates/restricted amd64 Packages [21.4 kB]
Get:72 http://archive.ubuntu.com/ubuntu trusty-updates/restricted i386 Packages [21.1 kB]
Get:73 http://archive.ubuntu.com/ubuntu trusty-updates/restricted Translation-en [3,706 B]
Get:74 http://archive.ubuntu.com/ubuntu trusty-updates/universe amd64 Packages [671 kB]
Get:75 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main amd64 Packages [20 B]
Get:76 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main i386 Packages [20 B]
Get:77 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main Translation-en [20 B]
Get:78 http://archive.ubuntu.com/ubuntu trusty-updates/universe i386 Packages [646 kB]
Get:79 http://archive.ubuntu.com/ubuntu trusty-updates/universe Translation-en [347 kB]
Get:80 http://archive.ubuntu.com/ubuntu trusty-updates/multiverse amd64 Packages [16.1 kB]
Get:81 http://archive.ubuntu.com/ubuntu trusty-updates/multiverse i386 Packages [16.6 kB]
Get:82 http://archive.ubuntu.com/ubuntu trusty-updates/multiverse Translation-en [7,680 B]
Get:64 http://archive.ubuntu.com/ubuntu trusty-updates/main amd64 Packages [1,177 kB]
Ign:64 http://archive.ubuntu.com/ubuntu trusty-updates/main amd64 Packages
Get:69 http://archive.ubuntu.com/ubuntu trusty-updates/main i386 Packages [1,089 kB]
Err:69 http://archive.ubuntu.com/ubuntu trusty-updates/main i386 Packages
  Hash Sum mismatch
Get:83 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty/main amd64 Packages [985 B]
Get:84 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty/main i386 Packages [985 B]
Get:85 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty/main Translation-en [644 B]
Get:86 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease [23.2 kB]
Get:87 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1,107 B]
Get:88 https://download.docker.com/linux/ubuntu trusty/stable amd64 Packages [5,957 B]
Err:64 http://archive.ubuntu.com/ubuntu trusty-updates/main amd64 Packages
  Writing more data than expected (1177774 > 1177297)
Get:89 http://archive.ubuntu.com/ubuntu trusty-backports/main Sources [10.4 kB]
Get:90 http://archive.ubuntu.com/ubuntu trusty-backports/restricted Sources [40 B]
Get:91 http://archive.ubuntu.com/ubuntu trusty-backports/universe Sources [41.3 kB]
Get:92 https://download.docker.com/linux/ubuntu trusty/edge amd64 Packages [7,106 B]
Get:93 http://archive.ubuntu.com/ubuntu trusty-backports/multiverse Sources [1,747 B]
Get:94 http://archive.ubuntu.com/ubuntu trusty-backports/main amd64 Packages [14.7 kB]
Get:95 http://archive.ubuntu.com/ubuntu trusty-backports/main i386 Packages [14.7 kB]
Get:96 http://archive.ubuntu.com/ubuntu trusty-backports/main Translation-en [7,426 B]
Get:97 http://archive.ubuntu.com/ubuntu trusty-backports/restricted amd64 Packages [40 B]
Get:98 http://archive.ubuntu.com/ubuntu trusty-backports/restricted i386 Packages [40 B]
Get:99 http://archive.ubuntu.com/ubuntu trusty-backports/restricted Translation-en [40 B]
Get:100 http://archive.ubuntu.com/ubuntu trusty-backports/universe amd64 Packages [52.5 kB]
Get:101 http://archive.ubuntu.com/ubuntu trusty-backports/universe i386 Packages [52.4 kB]
Get:102 http://archive.ubuntu.com/ubuntu trusty-backports/universe Translation-en [40.0 kB]
Get:103 http://archive.ubuntu.com/ubuntu trusty-backports/multiverse amd64 Packages [1,392 B]
Get:104 http://archive.ubuntu.com/ubuntu trusty-backports/multiverse i386 Packages [1,376 B]
Get:105 http://archive.ubuntu.com/ubuntu trusty-backports/multiverse Translation-en [1,165 B]
Get:106 http://archive.ubuntu.com/ubuntu trusty/main Sources [1,335 kB]
Ign:86 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease
Get:107 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty InRelease [23.7 kB]
Get:108 http://archive.ubuntu.com/ubuntu trusty/restricted Sources [5,335 B]
Get:109 http://archive.ubuntu.com/ubuntu trusty/universe Sources [7,926 kB]
Get:110 https://packagecloud.io/computology/apt-backport/ubuntu trusty/main Sources [843 B]
Get:111 http://archive.ubuntu.com/ubuntu trusty/multiverse Sources [211 kB]
Get:112 http://archive.ubuntu.com/ubuntu trusty/main amd64 Packages [1,743 kB]
Get:113 http://archive.ubuntu.com/ubuntu trusty/main i386 Packages [1,739 kB]
Get:114 http://archive.ubuntu.com/ubuntu trusty/restricted amd64 Packages [16.0 kB]
Get:115 http://archive.ubuntu.com/ubuntu trusty/restricted i386 Packages [16.4 kB]
Get:116 http://archive.ubuntu.com/ubuntu trusty/universe amd64 Packages [7,589 kB]
Get:117 http://archive.ubuntu.com/ubuntu trusty/universe i386 Packages [7,597 kB]
Get:118 https://packagecloud.io/computology/apt-backport/ubuntu trusty/main amd64 Packages [3,628 B]
Get:119 http://archive.ubuntu.com/ubuntu trusty/multiverse amd64 Packages [169 kB]
Get:120 http://archive.ubuntu.com/ubuntu trusty/multiverse i386 Packages [172 kB]
Get:121 https://packagecloud.io/computology/apt-backport/ubuntu trusty/main i386 Packages [848 B]
Get:122 https://packagecloud.io/github/git-lfs/ubuntu trusty/main Sources [20 B]
Get:123 https://packagecloud.io/github/git-lfs/ubuntu trusty/main amd64 Packages [8,003 B]
Get:124 https://packagecloud.io/github/git-lfs/ubuntu trusty/main i386 Packages [7,761 B]
Get:125 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty/main Sources [20 B]
Get:126 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty/main amd64 Packages [7,866 B]
Get:127 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty/main i386 Packages [7,866 B]
Fetched 38.0 MB in 4s (9,286 kB/s)
Reading package lists...
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
W: GPG error: https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
W: The repository 'https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease' is not signed.
W: There is no public key available for the following key IDs:
6B05F25D762E3157  
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Writing more data than expected (1177774 > 1177297)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-i386/Packages.bz2  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install mpich libmpich-dev libglib2.0-0 libgl1-mesa-glx qt5-default packagekit-gtk3-module libcanberra-gtk-module" failed and exited with 100 during .

**Comment by alejoe91** [comment]
Have you checked the Travis log? Do the test pass locally?

**Comment by alejoe91** [comment]
I rerun the test! Now there is a new error ;)

**Comment by alejoe91** [comment]
That was probably an error in downloading the package...it might happen

**Comment by colehurwitz** [comment]
Where did you run the test? I think I need all the sorters installed to run local tests?

**Comment by alejoe91** [comment]
I re run the build in Travis. You can click restart build. 
You can run the tests locally with pytest. It will skip the uninstalled ones.

**Comment by colehurwitz** [comment]
Oh, you right. I fix

**Comment by colehurwitz** [comment]
Have any default params changed in other pull requests that I should be worried about?

**Pull request merged**
