### PR TITLE
not working, added four letters

### PR DESCRIPTION
**Pull request by mhhennig**
it should be 'recording.dat', not 'recording'

### CODE REVIEW

**Comment by alejoe91** [comment]
.dati is appended by the write binary function :) but this is more explicit

**Comment by mhhennig** [comment]
No, it did not when I just tried - was using latest master for se as well.

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/extraction_tools.py#L288

**Comment by mhhennig** [comment]
honestly, I found a file called `recording` in ten working folder... *shrug*?

**Comment by alejoe91** [comment]
? I have used kilosort a lot and never found this issue :)

**Pull request merged**
