### PR TITLE
Very simple way to retrieve the version of the sorter.

### PR DESCRIPTION
**Pull request by samuelgarcia**
I have started a very simple way to retrieve version of each sorter.
The method is mandatory but for the moment it can return unknown.

It can be usefull for generated report like in SF or in "study".

I will need help for :
  * KS
  * KS2
  * MS4
  * IronClust
  * HS
 
Maybe we will have to make PR in upstream package.

What do you think ?

### CODE REVIEW

**Comment by magland** [comment]
That's a good idea. I should note that this is different from the spikeforest wrapper version. Both are useful. Could you put an issue into the ironclust repo (even though James is literally down the hall right now) and ask what's the best way to extract the version.

**Comment by samuelgarcia** [comment]
I known in SF there is a wrapper version, wich is also important because it define parameters.
We could also add this wrapper version concept here in spikesorters.
It demand te be very carrfull because it need to manually increment each time we change the wrapper.

**Comment by samuelgarcia** [comment]
ml_ms4alg do not have the \_\_version\_\_ ?

**Comment by samuelgarcia** [comment]
Also in SF you ensure version with docker.
Here it is more for user that run it on it own computer and want ot keep trace of benchmark versus version.

**Comment by magland** [comment]
Yes. But I'll point out that matlab sorters don't run in containers at this
time. Regardless, we are on the same page.

**Comment by samuelgarcia** [comment]
For matlab sorter we could ask to KS and KS2 dev to have a file in the code folder that contain the version as we do in sorter. SO it would be easy to parse. No ?

**Comment by magland** [comment]
Yes, we could ask that. It would be the easiest.

Thinking more about it, this is a very valuable feature for spikeforest --
will be very useful to auto print the version being used during run -- so
that when I inspect console output on web page I can know what was being
used.

**Comment by samuelgarcia** [comment]
oups I have accidentaly remove this before the merge, no ?

**Pull request closed without merging**
