### PR TITLE
Added docstrings for sorters and cleanup

### PR DESCRIPTION
**Pull request by alejoe91**
Added the option to retain only good units when running kilosort2. In order to to that I had to make the following modification: `get_results_from_folder` accepts a `params` argument

I also improved docstrings for the run sorter functions

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Alessio.
Not very happy with the modification of BaseSorter.
You inject the params dict in get_result_from_folder.
I don't like it so much.
Params in my mind is the params for computing not for retrieving.
Lets have a call.

**Comment by samuelgarcia** [comment]
And please : don't mix, comestics, docs and important small detail.
:)

**Comment by alejoe91** [comment]
That is the only way to pass a parameter to the extractor though...no?

**Comment by samuelgarcia** [comment]
Lets have a call.

**Comment by samuelgarcia** [comment]
Totally excelent cleaning.

**Pull request merged**
