### PR TITLE
Add "clean_catalogue_gui" for tridesclous in the middle of "run"

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by alejoe91** [comment]
Nice!! Should I merge?

**Comment by samuelgarcia** [comment]
Yep.
have you tried?

**Comment by alejoe91** [comment]
I'll try now

**Comment by alejoe91** [comment]
I don't know how to use the gui but it works!

**Comment by alejoe91** [comment]
I have to say! It is quite nice :) We just need to fix the number of automatic clusters.

**Comment by alejoe91** [comment]
merging :+1:

**Pull request merged**
